CurrencyCloud/currencycloud-swagger

src/reference.yaml
Implements cancellation, date change and conversion split functions in public documented API
=> Add conversion self-service functionality

src/reference.yaml
Re-order of calls for documentation generation.
Add missing mandatory parameter on conversion split preview.
=> WEB-68 conversion self service

src/reference.yaml
Add missing endpoint for authorising payment(s)
=> TCC-14379: Add /payments/authorise endpoint to documentation

src/reference.yaml
Remove on_behalf_of for HTTP POST /payments/authorise
=> TCC-14379 Remove on_behalf_of for HTTP POST /payments/authorise

src/reference.yaml
WIP on the ticket - Need to clarify example and if created/updated are needed
=> TCC-13268: Update Swagger for Sender Details API

src/reference.yaml
Add call to return Purpose Codes - Reference Data
=> TCC-14009: Add Reference data call for Purpose Codes

src/reference.yaml
For beneficiaries in India dealing with INR
=> TCC-13975: Add additional routing_code_type_1 entry 'ifsc'

src/reference.yaml, validate.rb
https://ccycloud.atlassian.net/browse/TCC-13748
=> TCC-13748: Find IBANs API

src/reference.yaml
https://ccycloud.atlassian.net/browse/TCC-13750
=> TCC-13750: Find VANs API

src/reference.yaml
=> TCC-15030: Add 'bank_account_country' for Payment Purpose Codes

src/reference.yaml
Reverts CurrencyCloud/currencycloud-swagger#27
=> Revert "TCC-15030: Update 'bank_account_country' for Payment Purpose Codes"

src/reference.yaml
The payment purpose code field field should be "purpose_code" instead of "payment_purpose_code".
=> TCC-15170 Fix payment purpose code field

src/reference.yaml
No API changes, just file formatting
=> Reformats swagger file to match api-gateway standard formatting

src/reference.yaml
Support for payment charge settings for /payments/create, /payments/find and /payment
=> SWAGGER-20 Support for Payment Charge Settings

README.md
Updates README to reflect release
=> Create a release branch for 2.0.0

src/reference.yaml
Adds enum and default values for scope parmeter on find-ibans and find-vans
=> SWAGGER-17 : Adds enum and default values for scope

src/reference.yaml
Updates documentation for transactions/find, payments/find and payments/create
=> SWAGGER-31 : Swagger doc fixes

src/reference.yaml
Move enum from beneficiary_identification_value to beneficiary_identification_type
=> TCC-15470 Create beneficiary enum list fix

src/reference.yaml
Fix beneficiary payment type default values. These should be strings.
=> SWAGGER-34 Fix Beneficiary Payment Type Defaults

README.md, src/reference.yaml
=> Updates Version in Swagger file to 2.2.0

src/reference.yaml
Moves enum list from beneficiary_identification_value to beneficiary_identification_type parameter parameter for beneficiary_create and beneficiary_validate
=> Moves enum list from beneficiary_identification_value to beneficiary_identification_type parameter

src/reference.yaml
id parameter actually represents related_entity_id
=> Updates the description of the id parameter of /v2/transactions/sender/{id}

src/reference.yaml
Update the x-deprecation-notes tag to provide a target date for the Settlement model to be deprecated.
=> SWAGGER-72 Deprecate Settlement Endpoints.

src/reference.yaml
Adds beneficiary_external_reference parameter to create and update beneficiary endpoints
=> Adds beneficiary_external_reference parameter

src/reference.yaml
- SWAGGER-88 : Adds get payment level fees endpoint
- SWAGGER-90 : Adds get quote payment fee endpoint
=> Adds get payment level fees endpoints

README.md, src/reference.yaml
- SWAGGER-116 : GET /v2/payments/payment_fees
- SWAGGER-117 : POST /v2/payments/assign_payment_fee
- SWAGGER-118 : POST /v2/payments/unassign_payment_fee
- SWAGGER-124 : Extends Get Payment Fee Rules response object
=> Adds new Payment level fee endpoints

src/reference.yaml
Small change to doc for conversion_date in create conversion API.
https://ccycloud.atlassian.net/jira/software/c/projects/SWAGGER/issues/SWAGGER-9
=> Swagger 9 update fx timezone doc

src/reference.yaml
Updates Beneficiary Identification Type to differentiate between company and individual.
=> SWAGGER-161 Beneficiary Identification Type

src/reference.yaml
This reverts commit 34354f05aca4648abb45ff64d2c4af875b41630e.
=> Revert "Removes parter_status from conversion endpoints SWAGGER-166"

src/reference.yaml
Adds offline_conversion_dates array to response
=> update reference get_conversion_dates endpoint response

src/reference.yaml
Adding terms_or_conditions accepted and agent_or_reliance paremeters to appropriate api calls.
=> Swagger-169

src/reference.yaml
Hi.  Could this be deployed to staging-1 in the first instance please.
=> Changes conversion endpoint descriptions.

src/reference.yaml
Related [**api-v2 pr**](https://github.com/ccycloud/api-v2/pull/392).
Related ticket: [**API-139**](https://ccycloud.atlassian.net/browse/API-139).
=> Add the +currency_pair_too_many_items+ error code to rates/find

src/reference.yaml
Could we deploy this to staging-1 in the first instance please.
=> Updates the description of payment purpose code

src/reference.yaml
related to the newly added error in Api-v2 https://github.com/ccycloud/api-v2/pull/524
=> [PRICE-774] add new error for /conversions/create and /rates/detailed

src/reference.yaml
Account model property aligned.
=> SWAGGER-251 Align terms and conditions accepted parameter in account model

POSTMAN_README.md
The existing link pointed to a 404 page.
=> Update API key registration link in POSTMAN_README.md

src/reference.yaml
This functionality will be going live later this week.
=> Adds two error message to create and update contact.

src/reference.yaml
Adds post endpoints for
accounts/find
beneficiaries/find
contacts/find
reference/bank_details
=> Adds post find endpoints
